pub const INPUT_BUTTON_UPPERCASE: &str = "INPUT_BUTTON ";
pub const INPUT_TOGGLE_UPPERCASE: &str = "INPUT_TOGGLE ";
pub const INPUT_SELECTION_UPPERCASE: &str = "INPUT_SELECTION ";
pub const INPUT_TEXT_UPPERCASE: &str = "INPUT_TEXT ";
pub const INPUT_DECIMAL_UPPERCASE: &str = "INPUT_DECIMAL ";
pub const INPUT_FILE_UPPERCASE: &str = "INPUT_FILE ";
pub const INPUT_RANGE_UPPERCASE: &str = "INPUT_RANGE ";

pub const RELEASE_LOWERCASE: &str = "release";
pub const DAILY_LOWERCASE: &str = "daily";
pub const PATCH_LOWERCASE: &str = "patch";

pub const ASC_LOWERCASE: &str = "asc";
pub const DESC_LOWERCASE: &str = "desc";

pub const PENDING_LOWERCASE: &str = "pending";
pub const DOWNLOADING_LOWERCASE: &str = "downloading";
pub const PAUSED_LOWERCASE: &str = "paused";
pub const COMPLETED_LOWERCASE: &str = "completed";
pub const FAILED_LOWERCASE: &str = "failed";

pub const RESET_DATABASE_UPPERCASE: &str = "RESET_DATABASE";
pub const SET_CHECK_INTERNET_CONNECTION_TIMEOUT_UPPERCASE: &str =
    "SET_CHECK_INTERNET_CONNECTION_TIMEOUT";
pub const CHECK_FOR_UPDATE_ON_LAUNCH_UPPERCASE: &str = "CHECK_FOR_UPDATE_ON_LAUNCH";
pub const CHECK_FOR_UPDATE_UPPERCASE: &str = "CHECK_FOR_UPDATE";
pub const OPEN_APP_VERSION_ONLINE_REPOSITORY_UPPERCASE: &str = "OPEN_APP_VERSION_ONLINE_REPOSITORY";
pub const OPEN_SYSTEM_CONSOLE_ON_LAUNCH_UPPERCASE: &str = "OPEN_SYSTEM_CONSOLE_ON_LAUNCH";
pub const CHANGE_ACTIVE_BLENDER_VERSION_THROUGH_TABLE_UPPERCASE: &str =
    "CHANGE_ACTIVE_BLENDER_VERSION_THROUGH_TABLE";
pub const MINIMIZE_BLENDERBASE_ON_LAUNCH_UPPERCASE: &str = "MINIMIZE_BLENDERBASE_ON_LAUNCH";
pub const PROCESS_ADDON_ON_LAUNCH_UPPERCASE: &str = "PROCESS_ADDON_ON_LAUNCH";
pub const SET_INSTALLED_BLENDER_VERSION_LIMIT_FOR_SCRAPING_UPPERCASE: &str =
    "SET_INSTALLED_BLENDER_VERSION_LIMIT_FOR_SCRAPING";
pub const INIT_BLENDER_DATA_ON_FIRST_INSTANCE_LAUNCH_UPPERCASE: &str =
    "INIT_BLENDER_DATA_ON_FIRST_INSTANCE_LAUNCH";
pub const REFRESH_BLENDER_DOWNLOAD_ON_LAUNCH_UPPERCASE: &str = "REFRESH_BLENDER_DOWNLOAD_ON_LAUNCH";
pub const DOWNLOAD_BLENDER_IN_DEFAULT_INSTALLATION_LOCATION_UPPERCASE: &str =
    "DOWNLOAD_BLENDER_IN_DEFAULT_INSTALLATION_LOCATION";
pub const SET_DOWNLOADABLE_BLENDER_VERSION_LIMIT_FOR_SCRAPING_UPPERCASE: &str =
    "SET_DOWNLOADABLE_BLENDER_VERSION_LIMIT_FOR_SCRAPING";
pub const SET_RECENT_FILES_BLENDER_SERIES_LIMIT_FOR_SCRAPING_UPPERCASE: &str =
    "SET_RECENT_FILES_BLENDER_SERIES_LIMIT_FOR_SCRAPING";
pub const CREATE_APP_LIBRARY_DIRECTORY_AUTOMATICALLY_UPPERCASE: &str =
    "CREATE_APP_LIBRARY_DIRECTORY_AUTOMATICALLY";

pub const NULL_UPPERCASE: &str = "NULL";
pub const INTEGER_UPPERCASE: &str = "INTEGER";
pub const STRING_UPPERCASE: &str = "STRING";
pub const FLOAT_UPPERCASE: &str = "FLOAT";
pub const BYTE_UPPERCASE: &str = "BYTE";
pub const CHAR_UPPERCASE: &str = "CHAR";
pub const JSON_UPPERCASE: &str = "JSON";
pub const XML_UPPERCASE: &str = "XML";
pub const BOOLEAN_UPPERCASE: &str = "BOOLEAN";
pub const BIT_UPPERCASE: &str = "BIT";
pub const DATE_UPPERCASE: &str = "DATE";
pub const TIME_UPPERCASE: &str = "TIME";
pub const DATETIME_UPPERCASE: &str = "DATETIME";
pub const TIMESTAMP_UPPERCASE: &str = "TIMESTAMP";
pub const BINARY_UPPERCASE: &str = "BINARY";
pub const UUID_UPPERCASE: &str = "UUID";
pub const ARRAY_UPPERCASE: &str = "ARRAY";
pub const OBJECT_UPPERCASE: &str = "OBJECT";
