name: Publish Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

concurrency:
  group: release
  cancel-in-progress: true

env:
  IBM_TELEMETRY_DISABLED: "true"
  SQLX_OFFLINE: "true"

jobs:
  publish-tauri:
    permissions:
      contents: write

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust build
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: src-tauri

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install frontend dependencies
        run: npm ci

      - name: Build and create GitHub Release
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__
          releaseName: Blenderbase v__VERSION__
          releaseBody: |
            Release notes: tba.
          releaseDraft: true
          prerelease: false
          includeUpdaterJson: false
